### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by aspnetcs** [Tanmay06/MedSearch#1]
how to run MedSearch, which is A content based image retrieval system using spark and mongoldb using android application as frontend.

phone :18656273986
e-mail: aspnetcs@163.com

**Comment by Tanmay06** [comment]
Hi,
Thank you for raising an issue, I have updated <a href="https://github.com/Tanmay06/MedSearch/blob/master/README.md">README.md</a> with all required information. If you want any further assistance you can raise an issue again.
